# Generated by Django 4.1.7 on 2023-03-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("roleMemURL", models.TextField()),
                ("isPublished", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spreadsheetIndex", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DatasourceColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("initialValue", models.TextField()),
                ("isLinkText", models.BooleanField()),
                ("isTableRef", models.BooleanField()),
                ("valueType", models.TextField()),
                (
                    "datasourceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s2a_api.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spreadsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s2a_api.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewPerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField()),
                ("allowedToView", models.BooleanField()),
                ("allowedToAdd", models.BooleanField()),
                ("allowedToEdit", models.BooleanField()),
                ("allowedToDelete", models.BooleanField()),
                (
                    "viewID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="s2a_api.view"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViewData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datasourceColumnID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s2a_api.datasourcecolumn",
                    ),
                ),
                (
                    "viewID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="s2a_api.view"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datasource",
            name="spreadsheetID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="s2a_api.spreadsheet"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="creatorID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="s2a_api.creator"
            ),
        ),
        migrations.CreateModel(
            name="AppData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s2a_api.application",
                    ),
                ),
                (
                    "datasourceID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s2a_api.datasource",
                    ),
                ),
            ],
        ),
    ]
