# Generated by Django 4.1.7 on 2023-03-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0005_rename_app_id_appdata_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailViewEditableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetailViewPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('detail_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.detailview')),
            ],
        ),
        migrations.CreateModel(
            name='TableViewPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('can_view', models.BooleanField()),
                ('can_add', models.BooleanField()),
                ('can_delete', models.BooleanField()),
                ('table_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.tableview')),
            ],
        ),
        migrations.CreateModel(
            name='TableViewViewableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='datasourcecolumn',
            name='is_editable',
        ),
        migrations.AddField(
            model_name='datasource',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ViewPerm',
        ),
        migrations.AddField(
            model_name='tableviewviewablecolumn',
            name='datasource_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasourcecolumn'),
        ),
        migrations.AddField(
            model_name='tableviewviewablecolumn',
            name='table_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.tableview'),
        ),
        migrations.AddField(
            model_name='detailvieweditablecolumn',
            name='datasource_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasourcecolumn'),
        ),
        migrations.AddField(
            model_name='detailvieweditablecolumn',
            name='detail_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.detailview'),
        ),
    ]
