# Generated by Django 4.1.7 on 2023-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0007_remove_datasource_spreadsheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='sheet_title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
