# Generated by Django 4.1.7 on 2023-03-31 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0009_rename_spreadsheet_index_datasource_gid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailview',
            name='datasource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasource'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppData',
        ),
    ]
