# Generated by Django 4.1.7 on 2023-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0010_remove_detailview_table_view_remove_tableview_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='spreadsheet_url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
