# Generated by Django 4.1.7 on 2023-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0011_remove_detailview_table_view_remove_tableview_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableviewperm',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='tableviewperm',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='tableviewperm',
            name='can_view',
        ),
        migrations.AddField(
            model_name='detailview',
            name='can_edit',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailview',
            name='can_view',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableview',
            name='can_add',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableview',
            name='can_delete',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableview',
            name='can_view',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='role_mem_url',
            field=models.TextField(null=True),
        ),
    ]
