# Generated by Django 4.1.7 on 2023-03-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role_mem_url', models.TextField()),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalDevelopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.application')),
                ('datasource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ViewPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('allowed_to_view', models.BooleanField()),
                ('allowed_to_add', models.BooleanField()),
                ('allowed_to_edit', models.BooleanField()),
                ('allowed_to_delete', models.BooleanField()),
                ('table_view_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.tableview')),
            ],
        ),
        migrations.CreateModel(
            name='DetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('record_index', models.IntegerField()),
                ('table_view_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.tableview')),
            ],
        ),
        migrations.CreateModel(
            name='DatasourceColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.IntegerField()),
                ('name', models.TextField()),
                ('initial_value', models.TextField()),
                ('value_type', models.TextField()),
                ('is_link_text', models.BooleanField()),
                ('is_table_ref', models.BooleanField()),
                ('is_filter', models.BooleanField()),
                ('is_user_filter', models.BooleanField()),
                ('is_edit_filter', models.BooleanField()),
                ('is_editable', models.BooleanField()),
                ('datasource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='spreadsheet_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.spreadsheet'),
        ),
        migrations.AddField(
            model_name='application',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.creator'),
        ),
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.application')),
                ('datasource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasource')),
            ],
        ),
    ]
