# Generated by Django 4.1.7 on 2023-03-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0002_alter_datasource_spreadsheet_id_alter_spreadsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='spreadsheet_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.spreadsheet'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
