# Generated by Django 4.1.7 on 2023-03-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0003_alter_datasource_spreadsheet_id_alter_spreadsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
