# Generated by Django 4.1.7 on 2023-03-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0004_alter_spreadsheet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdata',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='appdata',
            old_name='datasource_id',
            new_name='datasource',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='spreadsheet_id',
            new_name='spreadsheet',
        ),
        migrations.RenameField(
            model_name='datasourcecolumn',
            old_name='datasource_id',
            new_name='datasource',
        ),
        migrations.RenameField(
            model_name='detailview',
            old_name='table_view_id',
            new_name='table_view',
        ),
        migrations.RenameField(
            model_name='tableview',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='tableview',
            old_name='datasource_id',
            new_name='datasource',
        ),
        migrations.RenameField(
            model_name='viewperm',
            old_name='table_view_id',
            new_name='table_view',
        ),
    ]
