# Generated by Django 4.1.7 on 2023-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0006_detailvieweditablecolumn_detailviewperm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='spreadsheet',
        ),
        migrations.AddField(
            model_name='datasource',
            name='spreadsheet_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Spreadsheet',
        ),
    ]
