# Generated by Django 4.1.7 on 2023-04-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0009_rename_spreadsheet_index_datasource_gid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppData',
        ),
    ]
