# Generated by Django 4.2 on 2023-04-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0010_delete_appdata'),
        ('s2a_api', '0010_remove_detailview_table_view_remove_tableview_app_and_more'),
    ]

    operations = [
    ]
