# Generated by Django 4.1.7 on 2023-04-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0012_remove_detailview_table_view_remove_tableview_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailview',
            name='table_view',
        ),
        migrations.RemoveField(
            model_name='tableview',
            name='app',
        ),
    ]
