# Generated by Django 4.1.7 on 2023-04-10 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0013_remove_detailview_table_view_remove_tableview_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableview',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.application'),
            preserve_default=False,
        ),
    ]
