# Generated by Django 4.1.7 on 2023-04-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0014_auto_20230410_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailview',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='s2a_api.application'),
            preserve_default=False,
        ),
    ]
