# Generated by Django 4.1.7 on 2023-04-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0015_detailview_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailview',
            name='record_index',
        ),
    ]
