# Generated by Django 4.1.7 on 2023-04-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0016_remove_detailview_record_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailViewViewableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasourcecolumn')),
                ('detail_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.detailview')),
            ],
        ),
    ]
