# Generated by Django 4.1.7 on 2023-04-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2a_api', '0017_detailviewviewablecolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableViewFilterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.datasourcecolumn')),
                ('table_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s2a_api.tableview')),
            ],
        ),
    ]
