name: backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run
      run: |
        docker compose up -d --build

    - name: Test backend
      run: |
        sleep 20
        django_container_id=$(docker ps -q --filter "name=django")
        docker exec $django_container_id pytest -n logical
