name: frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run
      run: |
        sed -i "s/ENV REACT_APP_OAUTH_CLIENT_ID=.*/ENV REACT_APP_OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID/" client/Dockerfile
        sed -i "s/ENV OAUTH_CLIENT_ID=.*/ENV OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID/" server/Dockerfile
        sed -i "s/ENV OAUTH_CLIENT_SECRET=.*/ENV OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}/" server/Dockerfile
        docker compose up -d --build

    - name: Test
      run: |
        sleep 20
        frontend_container_id=$(docker ps -q --filter "name=node")
        docker exec $frontend_container_id npm run test -- --watchAll=false
